### ISSUE TITLE
Term of Use

### ISSUE THREAD

**Issue by typebrook** [osmfj/tileserver-gl-site#2]
Hi @osmfj @smellman , thanks for this awesome tile service!

When using style/tiles in other domain, is there any rules I should be aware of?

For example, using XYZ tiles with modern map library:
https://outdoorsafetylab.github.io/dumbymap/?content=tutorial

![Screenshot_2024-10-08-13-09-20_1920x1080](https://github.com/user-attachments/assets/440b8d67-7cbe-4222-a9fc-5e65eef4a4a3)

**Comment by smellman** [comment]
@typebrook free and no limit for use.
But I recommend to use vector style instead of raster tile.

**Comment by smellman** [comment]
@typebrook How about modify following:
```map
use: Maplibre
height: 120px
style: https://tile.openstreetmap.jp/styles/openmaptiles/style.json
```

**Comment by typebrook** [comment]
Sure, I'll update for this in next release
